# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
---
cache-min-ttl: 600
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 54
max-go-routines: 0
ratelimit: 0
ratelimit-subnet-len-ipv4: 24
ratelimit-subnet-len-ipv6: 64
udp-buf-size: 0
upstream:
  - "https://8.8.8.8/dns-query"
  - "https://8.8.4.4/dns-query"
upstream-mode: 'load_balance'
timeout: '30s'
